imports:
    - { resource: parameters.yml }

services:
    app.email_listener:
        class: AppBundle\EventListener\EmailListener
        arguments: ['@app.kafka_service']
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    app.kafka_service:
        class:     AppBundle\Services\KafkaService
        arguments:
            - %kafka_enable%
            - %kafka_host%
            - %kafka_port%
            - %kafka_topic%

framework:
    secret: '%secret_key%'
    form: ~
    assets: ~
    templating:
        engines: ['twig']
    serializer:
        enabled: true
        enable_annotations: true

doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        path:     %kernel.root_dir%/../%database_path%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true